### ISSUE TITLE
Only enable proxygen by default on recent versions of HHVM

### ISSUE THREAD

**Issue by fredemmott** [hhvm/oss-performance#45]

**Comment by reedy** [comment]
>= 3.8.0 then?

**Comment by fredemmott** [comment]
That sounds about right... though, HHVM is going to drop support for everything < 3.9 in January anyway, so this is nearly moot.

3.6 EOL: http://docs.hhvm.com/hhvm/installation/introduction#prebuilt-packages__lts-releases

3.7 became unsupported when 3.8 was released, 3.8 became unsupported when 3.9 was released.

**Comment by reedy** [comment]
Seems > at the start of the line is markdown syntax... Fixed above. Was going based on the blog post saying 3.8 has proxygen in it - http://hhvm.com/blog/9803/hhvm-3-8-0

Not too much of an issue; only reason I ended up using old ubuntu 12.04 was to get Siege 2, rather than having to build from source etc, or trying to forward port a potential dependency chain to get older seige on newer ubuntu (doesn't look too bad anyway). And of course, then only having packaged hhvm 3.6.6 to use.

#50 really needs fixing/investigating further before you drop full support for older HHVM versions!

Though, that doesn't help with Ubuntu much (without finding a ppa or similar), as even what is currently 16.04 has siege 3.0.8

Might have a play around to see if I can find a ppa/similar; else just try installing siege > 3.1 from source (hacking out the blacklist check) on newer ubuntu to test it out

**Comment by mofarrell** [comment]
We no longer support < 3.12.  I don't think this is important anymore, as it can be disabled manually anyways.
