### ISSUE TITLE
Add config management to setup testing instance

### ISSUE THREAD

**Issue by reedy** [hhvm/oss-performance#59]
it'd be really useful if there was a config for setting up the base machine to run these tests; even if its just the post install packages. using puppet or similar would be fine. hell. even a shell script would do

**Comment by quicksketch** [comment]
Agreed. I can't tell if this is supposed to set up nginx and the PHP versions or not.

From the README.md:

> This script sets up nginx, siege, and PHP5/PHP7/HHVM over FastCGI, over a TCP socket. Configuration is as close to identical as possible.

I can't find any script that sets up anything. Seems like you have to install PHP 5/7/HHVM manually and point the perf.php script at the executables.

**Comment by reedy** [comment]
It'll run PHP or HHVM using https://github.com/hhvm/oss-performance/blob/master/conf/php.ini as the config, and then something similar for nginx https://github.com/hhvm/oss-performance/tree/master/conf/nginx

I added in hacking in temporarily various debugging commands in https://github.com/hhvm/oss-performance/pull/57

And then I was just running

```
hhvm perf.php --mediawiki --hhvm=`which hhvm` --no-proxygen --i-am-not-benchmarking
```

I do like the version if your a FB employee... https://github.com/hhvm/oss-performance/blob/master/FB_EMPLOYEE_README.md

**Comment by fredemmott** [comment]
If someone maintains these in a separate repository, I'll be happy to link it. We won't do this (or merge pull requests for it) because:

 - we don't want to target/favor a specific distribution
 - config management is almost always distribution specific - while "how to install a package" is abstracted away, the names of the packages vary
 - this is made worse because most distributions do not ship a suitable version of Siege (though #50 may change that), so this would either have to include binaries per distro ('universal' binaries on linux are generally more work than per-distro packages) or know how to get that particular distribution's version of build-essentials and necessary -devel packages, and build Siege
 - maintaining them would be a really poor use of our time, compared to improving HHVM/Hack - this is why we wouldn't take merge requests; we don't distribute code that we don't want to support.

**Comment by fredemmott** [comment]
Also, the changes mentioned in cpu_freq.md and time_wait.md are very intrusive; I would not want to do these automatically without some very, very big warnings. Additionally, while the primary interface to them is distribution-agnostic, the 'correct' way to do them (so that they don't get automatically reverted) varies by distro.

If puppet/chef were used, you'd also need to make sure it doesn't run during a benchmark run (and it's usually running automatically every x minutes).

**Comment by quicksketch** [comment]
Cool, thanks for clarifying in https://github.com/hhvm/oss-performance/commit/53cb6cb9534a762ba1e3821b2bf9cc69ba1ace13. I spent an hour trying to figure out how this script was supposed to install PHP, not understanding that it was dependent on existing installations.

I've been using https://github.com/Kazanir/maat as a starting point to set up multiple versions of PHP on Ubuntu 14.04, which sets up a blank server with just about everything you need (including this oss-performance repository), but it's got some rough edges. The author said he hopes to clean it up in the near future. If polished, it would be a good straight-forward approach to getting a server set up so that this script could be used effectively. Background on that project can be found at http://kazanir.github.io/profiling/
